### ISSUE TITLE
Unable to start my Minecraft Server with Wunderreich installed

### ISSUE THREAD

**Issue by GeekyBakerBen** [quiqueck/wunderreich#16]
I have previously used Wunderreich ok, and recently have moved server, updated all my mods, and am starting with a completely brand new fresh server install and fresh new world.

Wunderreich v 6.0.4
Minecraft v 1.20.1
Fabric installer v 0.15.33

When I try and include Wunderreich in my mod selection now, I get the following in the server console when I try starting it up:

> [main/ERROR]: Failed to start the minecraft server
[03.01 14:45:32] [Server] java.lang.RuntimeExceptionCould not execute entrypoint stage 'main' due to errors, provided by 'wunderreich'!
[03.01 14:45:32] [Server] 	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:388) ~[fabric-loader-0.15.3.jar:?]
[03.01 14:45:32] [Server] 	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.15.3.jar:?]
[03.01 14:45:32] [Server] 	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:386) ~[fabric-loader-0.15.3.jar:?]
[03.01 14:45:32] [Server] 	at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63) ~[fabric-loader-0.15.3.jar:?]
[03.01 14:45:32] [Server] 	at net.minecraft.server.Main.main(Main.java:112) ~[server-intermediary.jar:?]
[03.01 14:45:32] [Server] 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.3.jar:?]
[03.01 14:45:32] [Server] 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.3.jar:?]
[03.01 14:45:32] [Server] 	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.15.3.jar:?]
[03.01 14:45:32] [Server] 	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.15.3.jar:?]
[03.01 14:45:32] [Server] 	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) ~[customjava17xms.jar:0.11.2]
[03.01 14:45:32] [Server] Caused byjava.lang.NoSuchFieldError: texture
[03.01 14:45:32] [Server] 	at de.ambertation.wunderreich.utils.WunderKisteDomain.<init>(WunderKisteDomain.java:75) ~[wunderreich-6.0.4.jar:?]
[03.01 14:45:32] [Server] 	at de.ambertation.wunderreich.utils.WunderKisteDomain.<clinit>(WunderKisteDomain.java:27) ~[wunderreich-6.0.4.jar:?]
[03.01 14:45:32] [Server] 	at de.ambertation.wunderreich.blocks.WunderKisteBlock.<clinit>(WunderKisteBlock.java:86) ~[wunderreich-6.0.4.jar:?]
[03.01 14:45:32] [Server] 	at de.ambertation.wunderreich.registries.WunderreichBlocks.lambda$static$0(WunderreichBlocks.java:30) ~[wunderreich-6.0.4.jar:?]
[03.01 14:45:32] [Server] 	at de.ambertation.wunderreich.registries.WunderreichBlocks.registerBlock(WunderreichBlocks.java:71) ~[wunderreich-6.0.4.jar:?]
[03.01 14:45:32] [Server] 	at de.ambertation.wunderreich.registries.WunderreichBlocks.<clinit>(WunderreichBlocks.java:27) ~[wunderreich-6.0.4.jar:?]
[03.01 14:45:32] [Server] 	at de.ambertation.wunderreich.registries.WunderreichBlockEntities.<clinit>(WunderreichBlockEntities.java:25) ~[wunderreich-6.0.4.jar:?]
[03.01 14:45:32] [Server] 	at de.ambertation.wunderreich.Wunderreich.onInitialize(Wunderreich.java:56) ~[wunderreich-6.0.4.jar:?]
[03.01 14:45:32] [Server] 	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384) ~[fabric-loader-0.15.3.jar:?]
[03.01 14:45:32] [Server] 	... more

I'm really no good with this sort of thing, but it looks like maybe it's having issues with a texture for the WunderKiste block or something? I don't know...

**Comment by SolidSneky** [comment]
I have _exactly_ the same issue :/

**Comment by nobully-osu** [comment]
same here

**Comment by AshdoII** [comment]
same issue exsisting. game version 1.20

**Comment by rgbeasley** [comment]
Same issue here, worked fine on single player, even hosting on LAN worked fine. Dedicated server not so much.

**Comment by Pleune** [comment]
Same here, does not work with recent fabric server, `java.lang.NoSuchFieldError: texture`

**Comment by keyschain** [comment]
same here

**Comment by WHiZSTA** [comment]
any updates on this? it's been months... im having the same issue 1.20.1 /w 6.0.4 and 6.0.3 on a dedicated server

**Comment by sammmsational** [comment]
Any update on this issue? It seems to have been patched with the merge, but I don't see a new build / release with that fix
