### ISSUE TITLE
The 1.21 version doesn't launch.

### ISSUE THREAD

**Issue by QuImUfu** [quiqueck/wunderreich#21]
The 1.21 alpha (tested all of them up to 21.0.2) doesn't launch, and logs following:
```
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'wunderreich'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:388)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:386)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(class_310.java:477)
	at net.minecraft.client.main.Main.main(Main.java:239)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.NoClassDefFoundError: net/minecraft/core/Registry
	at de.ambertation.wunderreich.Wunderreich.onInitialize(Wunderreich.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384)
	... 12 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.core.Registry
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	... 14 more
```

There seems to be some kind of re-obfuscation issue with wunderlib. (net.minecraft.core.Registry should be mapped to intermediary, but isn't). 

Thank you for your time.

**Comment by GanerCodes** [comment]
saem

**Comment by quiqueck** [comment]
Thanks you for reporting!
Could you please also post your mod-list? Does it crash for you if you only install wunderreich?

**Comment by QuImUfu** [comment]
Crashes with only wunderreich + fabric api.

**Comment by quiqueck** [comment]
Hm, strange that MultiMC handles the loading differently. Could you try if using the attached stand-alone version of wunderlib fixes the issue in MultiMC?

[wunderlib-21.0.6.jar.zip](https://github.com/user-attachments/files/16542216/wunderlib-21.0.6.jar.zip)

**Comment by QuImUfu** [comment]
adding that makes it work without any issue.

**Comment by quiqueck** [comment]
This should be fixed with the latest Wunderreich release (no need for an additional wunderlib file)
